/**
 * Dot-matrix base map for the landing screen (SAGAR-style dotted map).
 *
 * Generated once from Natural Earth 1:10m admin-0 countries, India point-of-view
 * edition (ne_10m_admin_0_countries_ind, public domain), so the outline follows
 * India's official boundary. Diagonal lattice, 0.4° spacing; odd rows are
 * offset by half a step. Each row is a string: 'i' = India, 'r' = neighbouring
 * land (drawn dimmer for context), '.' = sea / outside the frame.
 */
export const DOT_GRID = {
  west: 62.0, north: 38.0, step: 0.4,
  rows: [
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiirriiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrirriirrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiirrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiirrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrrrrirrrrrrrrrriiiiiiiiiiirrrr",
    "rrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrrrrrrrrrrirrrrrrriiiiiiiiiiiiiirrrr",
    "rrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrrrriirrrrrrrriiiiiiiiiirrirrrr",
    "rrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirirrrrrriiirririiiiiiiiiiirrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiriiiiiiiiiiiiiiiirrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrriiiiiiiiiiiiirrrrrrrrr",
    "rrrrrrrrrrrrrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrriiiiiiiiiiiirrrrrrrrrr",
    "rr..........rrrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrriiiiiiiiiiirrrrrrrrrr",
    ".............rrrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrrrrrrriiiiirrrrrrrrrrr",
    "..............rrrrrrrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrrrrrriiiiirrrrrrrrrrr",
    "..............rrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrriiiiirirrrrrrrrrrrr",
    ".................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrriiriiirrrrrrrrrrrrr",
    ".................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrr.rrrriirrrrrrrrrrrrrr",
    "...................i.iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrrrrrrirrrrrrrrrrrrrr",
    ".................i.iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrrr..rriirrrrrrrrrrrrrr",
    "..................iiiiiiii.iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrr....rrrrrrrrrrrrrrrrr",
    "...................iiiiiii.iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii...........rrrrrrrrrrrrrrrrr",
    ".....................iiiii.iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii.............rrrrrrrrrrrrrrrr",
    ".....................ii....iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii..............rrrrrrrrrrrrrrrr",
    "............................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii...............rrrrrrrrrrrrrr",
    "...........................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii..................rrrrrrrrrrrrr",
    "...........................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii......................rrrrrrrrrrrr",
    "...........................iiiiiiiiiiiiiiiiiiiiiiiiiiiiii......................rrrrrrrrrrrrr",
    "............................iiiiiiiiiiiiiiiiiiiiiiiiiiiii......................r.rrrrrrrrrrr",
    "...........................iiiiiiiiiiiiiiiiiiiiiiiiiiii..........................rrrrrrrrrrr",
    "............................iiiiiiiiiiiiiiiiiiiiiiiiii............................rrrrrrrrrr",
    "............................iiiiiiiiiiiiiiiiiiiiiiiii............................rrrrrrrrrrr",
    ".............................iiiiiiiiiiiiiiiiiiiiiii..............................rrrrrrrrrr",
    "............................iiiiiiiiiiiiiiiiiiiiiii..............................rrrrrr.rrrr",
    ".............................iiiiiiiiiiiiiiiiiiiii...............................rrrrr....rr",
    ".............................iiiiiiiiiiiiiiiiiii.................................rrr.....rrr",
    "..............................iiiiiiiiiiiiiiii............................................rr",
    "..............................iiiiiiiiiiiiiii.............................................rr",
    "...............................iiiiiiiiiiiiiii............................................rr",
    "...............................iiiiiiiiiiiiii.............................................rr",
    "................................iiiiiiiiiiiiii.............................................r",
    "................................iiiiiiiiiiiii..............................................r",
    "................................iiiiiiiiiiiiii..............................................",
    "................................iiiiiiiiiiiiii..............................................",
    ".................................iiiiiiiiiiiii...............................i.............r",
    ".................................iiiiiiiiiiii................................i..............",
    "..................................iiiiiiiiiii...............................................",
    "..................................iiiiiiiiiii...............................................",
    "...................................iiiiiiiiii...............................................",
    "...................................iiiiiiiiii..............................................r",
    "....................................iiiiiiii................................................",
    "....................................iiiiii.................................................r",
    ".....................................iiiii....rr.............................i.............r",
    ".....................................iii.....rrr...........................................r",
    "......................................iii....rrrr..........................................r",
    ".............................................rrrr...........................................",
    ".............................................rrrrr..........................................",
    ".............................................rrrrr.............................i............",
    ".............................................rrrrr..........................................",
    ".............................................rrrr...........................................",
    "..............................................r.............................................",
    "...................................................................................r........",
  ],
};
